#!/usr/bin/env bash

clone() {
  src="$1"
  dst="${2-$( basename $src )}"
  if [[ ! -e "$dst" ]]; then
      git clone "git@github.com:${src}.git" "$dst"
  fi
}

mkdir -p misc/modules

clone ${ROCK_PYTHON-rockstack/rock}
clone ${ROCK_PACKAGES-rockstack/packages}
clone ${ROCK_HOMEBREW-rockstack/homebrew-rock} homebrew
clone ${ROCK_TESTS-rockstack/tests}
clone ${ROCK_SITE-rockstack/rockstack.github.com} site
clone ${ROCK_UTILS-rockstack/utils} utils
clone ${ROCK_DOCKERFILES-rockstack/dockerfiles}

clone ${ROCK_RUNTIME_NODE08-rockstack/rock-runtime-node08} runtime-node08
clone ${ROCK_RUNTIME_NODE010-rockstack/rock-runtime-node010} runtime-node010
clone ${ROCK_RUNTIME_PERL516-rockstack/rock-runtime-perl516} runtime-perl516
clone ${ROCK_RUNTIME_PERL518-rockstack/rock-runtime-perl518} runtime-perl518
clone ${ROCK_RUNTIME_PHP54-rockstack/rock-runtime-php54} runtime-php54
clone ${ROCK_RUNTIME_PHP55-rockstack/rock-runtime-php55} runtime-php55
clone ${ROCK_RUNTIME_PYTHON27-rockstack/rock-runtime-python27} runtime-python27
clone ${ROCK_RUNTIME_PYTHON33-rockstack/rock-runtime-python33} runtime-python33
clone ${ROCK_RUNTIME_RUBY18-rockstack/rock-runtime-ruby18} runtime-ruby18
clone ${ROCK_RUNTIME_RUBY19-rockstack/rock-runtime-ruby19} runtime-ruby19
clone ${ROCK_RUNTIME_RUBY20-rockstack/rock-runtime-ruby20} runtime-ruby20
