#!/usr/bin/env bash

clone() {
  src="$1"
  dst="${2-$( basename $src )}"
  if [[ ! -e "$dst" ]]; then
      git clone "git@github.com:${src}.git" "$dst"
  fi
}

mkdir -p misc/modules

clone ${ROCK_PYTHON-rockplatform/python-rock}
clone ${ROCK_PACKAGES-rockplatform/packages}
clone ${ROCK_PUPPET-rockplatform/puppet-rock} misc/modules/rock
clone ${ROCK_TESTS-rockplatform/tests}
clone ${ROCK_TOOLS-rockplatform/tools}

vagrant up
