#!/usr/bin/env bash

path="${1:$( pwd )}"
deps_path="${path}/carton.lock"

if [[ ! -f "$deps_path" ]]; then
  echo "File not found: $deps_path" >&2
  exit 1
fi

if ! cd "$path"; then
  exit 1
fi

if ! carton --deployment >&2; then
  exit 1
fi
