#!/usr/bin/env bash

path="${1:$( pwd )}"
deps_path="${path}/vendor/virtualenv"
file_path="${path}/requirements.txt"

if [[ ! -f "$file_path" ]]; then
  echo "File not found: ${file_path}" >&2
  exit 1
fi

if ! cd "$path"; then
  exit 1
fi

if [[ ! -f "${deps_path}/bin/activate" ]]; then
  if ! virtualenv "$deps_path" >&2; then
    exit 1
  fi
fi

if ! (. "${deps_path}/bin/activate" && pip install -r "$file_path") >&2; then
  exit 1
fi

echo -n "$deps_path"
