#!/usr/bin/env bash

path="${1-$( pwd )}"
deps_path="${path}/local"
file_path="${path}/carton.lock"

if [[ ! -f "$file_path" ]]; then
  echo "File not found: $file_path" >&2
  exit 1
fi

if ! cd "$path"; then
  exit 1
fi

if ! carton install --deployment >&2; then
  exit 1
fi

echo -n "$deps_path"
