#!/usr/bin/env bash

set -e

path="${1-$( pwd )}"
deps_path="${path}/vendor/virtualenv"
file_path="${path}/requirements.txt"

if [[ ! -f "$file_path" ]]; then
  echo "File not found: ${file_path}" >&2
  exit 1
fi

cd "$path"

if [[ ! -f "${deps_path}/bin/activate" ]]; then
  virtualenv "$deps_path" >&2
fi

(. "${deps_path}/bin/activate" && pip install -r "$file_path") >&2

echo -n "$deps_path"
