#!/usr/bin/env bash

BUILD_PATH='/tmp/rock'
CACHE_PATH="${BUILD_PATH}/cache"
ROCK_PATH='/opt/rock'

runtime_path() {
  echo "${ROCK_PATH}/runtime/$1"
}

runtime_setup() {
  local name="$1"
  local path="$( runtime_path $name )"

  rm -fr "$path"
  mkdir -p "$path"
}

build_path() {
  echo "/tmp/rock/$1"
}

build_setup() {
  local name="$1" ; shift
  local urls="$@"

  [[ -n "$name" ]]
  [[ -n "$urls" ]]

  local path="$( build_path $name )"

  mkdir -p "${CACHE_PATH}"

  rm -fr "$path"
  mkdir -p "$path"

  local url

  for url in $urls; do
    local file="$( basename "$url" )"
    local file_path="${CACHE_PATH}/${file}"

    [[ -f "$file_path" ]] || curl -L "$url" -o "$file_path"
    [[ -f "${path}/${file}" ]] || ln "$file_path" "${path}/${file}"
  done
}

setup() {
  local name="$1" ; shift
  local urls="$@"

  build_setup "$name" "$@"
  runtime_setup "$name"
}
