#!/usr/bin/env bash

ROOT="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" ; . "$ROOT/lib" ; set -ve

name='node04'
version='0.4.12'
url="http://nodejs.org/dist/node-v${version}.tar.gz"
npm_version='1.0.106'
npm_url="http://registry.npmjs.org/npm/-/npm-${npm_version}.tgz"

src_path="$( build_path $name )"
dst_path="$( runtime_path $name )"

setup "$name" "$url" "$npm_url"

pushd "$src_path"
  tar -xzf "$( basename "$url" )"
  tar -xzf "$( basename "$npm_url" )"

  pushd "node-v${version}"
    ./configure --prefix="${dst_path}/usr"
    make install
  popd

  pushd 'package'
    export PATH="${dst_path}/usr/bin:$PATH"
    ./configure --prefix="${dst_path}/usr"
    make install
    echo "prefix = ${dst_path}/usr" > "${dst_path}/usr/lib/node_modules/npm/npmrc"
  popd
popd

cat << EOF > "${dst_path}/rock.yml"
env:
  PATH: "${dst_path}/usr/bin:\${PATH}"
EOF
