#!/usr/bin/env bash

ROOT="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" ; . "$ROOT/lib" ; set -ve

name='node06'
version='0.6.21'
url="http://nodejs.org/dist/v${version}/node-v${version}.tar.gz"

src_path="$( build_path $name )"
dst_path="$( runtime_path $name )"

setup "$name" "$url"

pushd "$src_path"
  tar -xzf "$( basename "$url" )"

  pushd "node-v${version}"
    ./configure --prefix="${dst_path}/usr"
    make install
  popd
popd

cat << EOF > "${dst_path}/rock.yml"
env:
  PATH: "${dst_path}/usr/bin:\${PATH}"
EOF
